export const full1 = {
	name: 'full',
	rounds: 6,
	roundStart: 'D',
	mapShape: 'W',
	greenTiles: 7,
	brownTiles: 4,
	cityTiles: 2,
	cityLevels: [5,8],
	cityColors: null,
	dummy: 'standard solo',
	tactics: 'after2',
	ending: 'Last city conquered',
	scoring: 'fame + achievements + time + bonus + coop goal[cities]',
	special: null,
	filtering: {
		mapG: [['BG'],[]],
		mapB: [['BG'],[]],
		mapC: [['BG'],[]],
		advancedAction: [[],[]],
		spell: [[],[]],
		artifact: [[],[]],
		unit: [[],[]],
		skill: [[],[]],
	}
}

export const fullCoop2 = {
	name: 'full',
	rounds: 6,
	roundStart: 'D',
	mapShape: 'O',
	greenTiles: 8,
	brownTiles: 5,
	cityTiles: 3,
	cityLevels: [5,5,8],
	cityColors: null,
	dummy: 'standard',
	tactics: 'first1',
	ending: 'Last city conquered',
	scoring: 'min fame + max achievements + time bonus + coop goal[cities] + Add 10 if all players are leaders of a city',
	special: null,
	filtering: {
		mapG: [['BG'],[]],
		mapB: [['BG'],[]],
		mapC: [['BG'],[]],
		advancedAction: [[],[]],
		spell: [[],[]],
		artifact: [[],[]],
		unit: [[],[]],
		skill: [[],[]],
	}
}

export const fullCoop3 = {
	name: 'full',
	rounds: 6,
	roundStart: 'D',
	mapShape: 'O',
	greenTiles: 10,
	brownTiles: 7,
	cityTiles: 4,
	cityLevels: [5,5,5,11],
	cityColors: null,
	dummy: 'standard',
	tactics: 'first1',
	ending: 'Last city conquered',
	scoring: 'min fame + max achievements + time bonus + coop goal[cities] + Add 10 if all players are leaders of a city',
	special: null,
	filtering: {
		mapG: [['BG'],[]],
		mapB: [['BG'],[]],
		mapC: [['BG'],[]],
		advancedAction: [[],[]],
		spell: [[],[]],
		artifact: [[],[]],
		unit: [[],[]],
		skill: [[],[]],
	}
}

export const fullConquest2 = {
	name: 'full',
	rounds: 6,
	roundStart: 'D',
	mapShape: 'W',
	greenTiles: 8,
	brownTiles: 3,
	cityTiles: 2,
	cityLevels: [4,4],
	cityColors: null,
	dummy: null,
	tactics: 'normal',
	ending: 'Last city conquered',
	scoring: 'fame + achievements + titles + goal[cities]',
	special: null,
	filtering: {
		mapG: [['BG'],[]],
		mapB: [['BG'],[]],
		mapC: [['BG'],[]],
		advancedAction: [[],[]],
		spell: [[],[]],
		artifact: [[],[]],
		unit: [[],[]],
		skill: [[],[]],
	}
}

export const fullConquest3 = {
	name: 'full',
	rounds: 6,
	roundStart: 'D',
	mapShape: 'W',
	greenTiles: 9,
	brownTiles: 5,
	cityTiles: 3,
	cityLevels: [4,4,4],
	cityColors: null,
	dummy: null,
	tactics: 'normal',
	ending: 'Last city conquered',
	scoring: 'fame + achievements + titles + goal[cities]',
	special: null,
	filtering: {
		mapG: [['BG'],[]],
		mapB: [['BG'],[]],
		mapC: [['BG'],[]],
		advancedAction: [[],[]],
		spell: [[],[]],
		artifact: [[],[]],
		unit: [[],[]],
		skill: [[],[]],
	}
}

export const fullConquest4 = {
	name: 'full',
	rounds: 6,
	roundStart: 'D',
	mapShape: 'O',
	greenTiles: 11,
	brownTiles: 7,
	cityTiles: 4,
	cityLevels: [4,4,4,4],
	cityColors: null,
	dummy: null,
	tactics: 'normal',
	ending: 'Last city conquered',
	scoring: 'fame + achievements + titles + goal[cities]',
	special: null,
	filtering: {
		mapG: [['BG'],[]],
		mapB: [['BG'],[]],
		mapC: [['BG'],[]],
		advancedAction: [[],[]],
		spell: [[],[]],
		artifact: [[],[]],
		unit: [[],[]],
		skill: [[],[]],
	}
}
