export default city = [
	{
		name: 'Freezers',
		tokenNumber: 13,
		physicalAttack: 0,
		fireAttack: 0,
		iceAttack: 3,
		coldFireAttack: 0,
		defense: 7,
		fame: 7,
		fortified: false,
		physicalResist: false,
		fireResist: true,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: false,
		paralyze: true,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Freezers',
		tokenNumber: 13,
		physicalAttack: 0,
		fireAttack: 0,
		iceAttack: 3,
		coldFireAttack: 0,
		defense: 7,
		fame: 7,
		fortified: false,
		physicalResist: false,
		fireResist: true,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: false,
		paralyze: true,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Freezers',
		tokenNumber: 13,
		physicalAttack: 0,
		fireAttack: 0,
		iceAttack: 3,
		coldFireAttack: 0,
		defense: 7,
		fame: 7,
		fortified: false,
		physicalResist: false,
		fireResist: true,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: false,
		paralyze: true,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Gunners',
		tokenNumber: 14,
		physicalAttack: 0,
		fireAttack: 6,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 6,
		fame: 7,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Gunners',
		tokenNumber: 14,
		physicalAttack: 0,
		fireAttack: 6,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 6,
		fame: 7,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Gunners',
		tokenNumber: 14,
		physicalAttack: 0,
		fireAttack: 6,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 6,
		fame: 7,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Altem Guardsmen',
		tokenNumber: 15,
		physicalAttack: 6,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 7,
		fame: 8,
		fortified: true,
		physicalResist: true,
		fireResist: true,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Altem Guardsmen',
		tokenNumber: 15,
		physicalAttack: 6,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 7,
		fame: 8,
		fortified: true,
		physicalResist: true,
		fireResist: true,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Altem Mages',
		tokenNumber: 16,
		physicalAttack: 0,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 4,
		defense: 8,
		fame: 8,
		fortified: true,
		physicalResist: true,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: true,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Altem Mages',
		tokenNumber: 16,
		physicalAttack: 0,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 4,
		defense: 8,
		fame: 8,
		fortified: true,
		physicalResist: true,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: true,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	}
];