export default city = [
	{
		name: 'Freezers',
		number: 13,
		attack: {
			normal: 0,
			fire: 0,
			ice: 3,
			coldFire: 0
		},
		defense: 7,
		fame: 7,
		fortified: false,
		physicalResist: false,
		fireResist: true,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: false,
		paralyze: true,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Freezers',
		number: 13,
		attack: {
			normal: 0,
			fire: 0,
			ice: 3,
			coldFire: 0
		},
		defense: 7,
		fame: 7,
		fortified: false,
		physicalResist: false,
		fireResist: true,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: false,
		paralyze: true,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Freezers',
		number: 13,
		attack: {
			normal: 0,
			fire: 0,
			ice: 3,
			coldFire: 0
		},
		defense: 7,
		fame: 7,
		fortified: false,
		physicalResist: false,
		fireResist: true,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: false,
		paralyze: true,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Gunners',
		number: 14,
		attack: {
			normal: 0,
			fire: 6,
			ice: 0,
			coldFire: 0
		},
		defense: 6,
		fame: 7,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Gunners',
		number: 14,
		attack: {
			normal: 0,
			fire: 6,
			ice: 0,
			coldFire: 0
		},
		defense: 6,
		fame: 7,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Gunners',
		number: 14,
		attack: {
			normal: 0,
			fire: 6,
			ice: 0,
			coldFire: 0
		},
		defense: 6,
		fame: 7,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Altem Guardsmen',
		number: 15,
		attack: {
			normal: 6,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 7,
		fame: 8,
		fortified: true,
		physicalResist: true,
		fireResist: true,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Altem Guardsmen',
		number: 15,
		attack: {
			normal: 6,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 7,
		fame: 8,
		fortified: true,
		physicalResist: true,
		fireResist: true,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Altem Mages',
		number: 16,
		attack: {
			normal: 0,
			fire: 0,
			ice: 0,
			coldFire: 4
		},
		defense: 8,
		fame: 8,
		fortified: true,
		physicalResist: true,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: true,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Altem Mages',
		number: 16,
		attack: {
			normal: 0,
			fire: 0,
			ice: 0,
			coldFire: 4
		},
		defense: 8,
		fame: 8,
		fortified: true,
		physicalResist: true,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: true,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	}
];