export default draconum = [
	{
		name: 'Swamp Dragon',
		tokenNumber: 26,
		physicalAttack: 5,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 9,
		fame: 7,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: true,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Swamp Dragon',
		tokenNumber: 26,
		physicalAttack: 5,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 9,
		fame: 7,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: true,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Fire Dragon',
		tokenNumber: 27,
		physicalAttack: 0,
		fireAttack: 9,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 7,
		fame: 8,
		fortified: false,
		physicalResist: true,
		fireResist: true,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Fire Dragon',
		tokenNumber: 27,
		physicalAttack: 0,
		fireAttack: 9,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 7,
		fame: 8,
		fortified: false,
		physicalResist: true,
		fireResist: true,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Ice Dragon',
		tokenNumber: 28,
		physicalAttack: 0,
		fireAttack: 0,
		iceAttack: 6,
		coldFireAttack: 0,
		defense: 7,
		fame: 8,
		fortified: false,
		physicalResist: true,
		fireResist: false,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: true,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Ice Dragon',
		tokenNumber: 28,
		physicalAttack: 0,
		fireAttack: 0,
		iceAttack: 6,
		coldFireAttack: 0,
		defense: 7,
		fame: 8,
		fortified: false,
		physicalResist: true,
		fireResist: false,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: true,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'High Dragon',
		tokenNumber: 29,
		physicalAttack: 0,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 6,
		defense: 9,
		fame: 9,
		fortified: false,
		physicalResist: false,
		fireResist: true,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'High Dragon',
		tokenNumber: 29,
		physicalAttack: 0,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 6,
		defense: 9,
		fame: 9,
		fortified: false,
		physicalResist: false,
		fireResist: true,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	}
];