export default draconum = [
	{
		name: 'Swamp Dragon',
		number: 26,
		attack: {
			normal: 5,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 9,
		fame: 7,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: true,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Swamp Dragon',
		number: 26,
		attack: {
			normal: 5,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 9,
		fame: 7,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: true,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Fire Dragon',
		number: 27,
		attack: {
			normal: 0,
			fire: 9,
			ice: 0,
			coldFire: 0
		},
		defense: 7,
		fame: 8,
		fortified: false,
		physicalResist: true,
		fireResist: true,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Fire Dragon',
		number: 27,
		attack: {
			normal: 0,
			fire: 9,
			ice: 0,
			coldFire: 0
		},
		defense: 7,
		fame: 8,
		fortified: false,
		physicalResist: true,
		fireResist: true,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Ice Dragon',
		number: 28,
		attack: {
			normal: 0,
			fire: 0,
			ice: 6,
			coldFire: 0
		},
		defense: 7,
		fame: 8,
		fortified: false,
		physicalResist: true,
		fireResist: false,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: true,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Ice Dragon',
		number: 28,
		attack: {
			normal: 0,
			fire: 0,
			ice: 6,
			coldFire: 0
		},
		defense: 7,
		fame: 8,
		fortified: false,
		physicalResist: true,
		fireResist: false,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: true,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'High Dragon',
		number: 29,
		attack: {
			normal: 0,
			fire: 0,
			ice: 0,
			coldFire: 6
		},
		defense: 9,
		fame: 9,
		fortified: false,
		physicalResist: false,
		fireResist: true,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'High Dragon',
		number: 29,
		attack: {
			normal: 0,
			fire: 0,
			ice: 0,
			coldFire: 6
		},
		defense: 9,
		fame: 9,
		fortified: false,
		physicalResist: false,
		fireResist: true,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	}
];