export default dungeon = [
	{
		name: 'Minotaur',
		number: 21,
		attack: {
			normal: 5,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 5,
		fame: 4,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Minotaur',
		number: 21,
		attack: {
			normal: 5,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 5,
		fame: 4,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Gargoyle',
		number: 22,
		attack: {
			normal: 5,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 4,
		fame: 4,
		fortified: false,
		physicalResist: true,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Gargoyle',
		number: 22,
		attack: {
			normal: 5,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 4,
		fame: 4,
		fortified: false,
		physicalResist: true,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Medusa',
		number: 23,
		attack: {
			normal: 6,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 4,
		fame: 5,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: true,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Medusa',
		number: 23,
		attack: {
			normal: 6,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 4,
		fame: 5,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: true,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Crypt Worm',
		number: 24,
		attack: {
			normal: 6,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 6,
		fame: 5,
		fortified: true,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Crypt Worm',
		number: 24,
		attack: {
			normal: 6,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 6,
		fame: 5,
		fortified: true,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Werewolf',
		number: 25,
		attack: {
			normal: 7,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 5,
		fame: 5,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Werewolf',
		number: 25,
		attack: {
			normal: 7,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 5,
		fame: 5,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	}
];