export default keep = [
	{
		name: 'Crossbowmen',
		number: 17,
		attack: {
			normal: 4,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 4,
		fame: 3,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Crossbowmen',
		number: 17,
		attack: {
			normal: 4,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 4,
		fame: 3,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Crossbowmen',
		number: 17,
		attack: {
			normal: 4,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 4,
		fame: 3,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Guardsmen',
		number: 18,
		attack: {
			normal: 3,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 7,
		fame: 3,
		fortified: true,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Guardsmen',
		number: 18,
		attack: {
			normal: 3,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 7,
		fame: 3,
		fortified: true,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Guardsmen',
		number: 18,
		attack: {
			normal: 3,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 7,
		fame: 3,
		fortified: true,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Swordsmen',
		number: 19,
		attack: {
			normal: 6,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 5,
		fame: 4,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Swordsmen',
		number: 19,
		attack: {
			normal: 6,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 5,
		fame: 4,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Golems',
		number: 20,
		attack: {
			normal: 2,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 5,
		fame: 4,
		fortified: true,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Golems',
		number: 20,
		attack: {
			normal: 2,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 5,
		fame: 4,
		fortified: true,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	
];