export default mageTower = [
	{
		name: 'Monks',
		tokenNumber: 7,
		physicalAttack: 5,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 5,
		fame: 4,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: true,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Monks',
		tokenNumber: 7,
		physicalAttack: 5,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 5,
		fame: 4,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: true,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Ice Mages',
		tokenNumber: 8,
		physicalAttack: 0,
		fireAttack: 0,
		iceAttack: 5,
		coldFireAttack: 0,
		defense: 6,
		fame: 5,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Ice Mages',
		tokenNumber: 8,
		physicalAttack: 0,
		fireAttack: 0,
		iceAttack: 5,
		coldFireAttack: 0,
		defense: 6,
		fame: 5,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Fire Mages',
		tokenNumber: 9,
		physicalAttack: 0,
		fireAttack: 6,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 5,
		fame: 5,
		fortified: false,
		physicalResist: false,
		fireResist: true,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Fire Mages',
		tokenNumber: 9,
		physicalAttack: 0,
		fireAttack: 6,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 5,
		fame: 5,
		fortified: false,
		physicalResist: false,
		fireResist: true,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Illusionists',
		tokenNumber: 10,
		physicalAttack: 0,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 3,
		fame: 4,
		fortified: false,
		physicalResist: true,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: true,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Illusionists',
		tokenNumber: 10,
		physicalAttack: 0,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 3,
		fame: 4,
		fortified: false,
		physicalResist: true,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: true,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Ice Golems',
		tokenNumber: 11,
		physicalAttack: 0,
		fireAttack: 0,
		iceAttack: 2,
		coldFireAttack: 0,
		defense: 4,
		fame: 5,
		fortified: false,
		physicalResist: true,
		fireResist: false,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: true,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Fire Golems',
		tokenNumber: 12,
		physicalAttack: 0,
		fireAttack: 3,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 4,
		fame: 5,
		fortified: false,
		physicalResist: true,
		fireResist: true,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
];