export default mageTower = [
	{
		name: 'Monks',
		number: 7,
		attack: {
			normal: 5,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 5,
		fame: 4,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: true,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Monks',
		number: 7,
		attack: {
			normal: 5,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 5,
		fame: 4,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: true,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Ice Mages',
		number: 8,
		attack: {
			normal: 0,
			fire: 0,
			ice: 5,
			coldFire: 0
		},
		defense: 6,
		fame: 5,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Ice Mages',
		number: 8,
		attack: {
			normal: 0,
			fire: 0,
			ice: 5,
			coldFire: 0
		},
		defense: 6,
		fame: 5,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Fire Mages',
		number: 9,
		attack: {
			normal: 0,
			fire: 6,
			ice: 0,
			coldFire: 0
		},
		defense: 5,
		fame: 5,
		fortified: false,
		physicalResist: false,
		fireResist: true,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Fire Mages',
		number: 9,
		attack: {
			normal: 0,
			fire: 6,
			ice: 0,
			coldFire: 0
		},
		defense: 5,
		fame: 5,
		fortified: false,
		physicalResist: false,
		fireResist: true,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Illusionists',
		number: 10,
		attack: {
			normal: 0,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 3,
		fame: 4,
		fortified: false,
		physicalResist: true,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: true,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Illusionists',
		number: 10,
		attack: {
			normal: 0,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 3,
		fame: 4,
		fortified: false,
		physicalResist: true,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: true,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Ice Golems',
		number: 11,
		attack: {
			normal: 0,
			fire: 0,
			ice: 2,
			coldFire: 0
		},
		defense: 4,
		fame: 5,
		fortified: false,
		physicalResist: true,
		fireResist: false,
		iceResist: true,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: true,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Fire Golems',
		number: 12,
		attack: {
			normal: 0,
			fire: 3,
			ice: 0,
			coldFire: 0
		},
		defense: 4,
		fame: 5,
		fortified: false,
		physicalResist: true,
		fireResist: true,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
];