export default mauraudingOrcs = [
	{
		name: 'Prowlers',
		tokenNumber: 1,
		physicalAttack: 4,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 3,
		fame: 2,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Prowlers',
		tokenNumber: 1,
		physicalAttack: 4,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 3,
		fame: 2,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Diggers',
		tokenNumber: 2,
		physicalAttack: 3,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 3,
		fame: 2,
		fortified: true,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Diggers',
		tokenNumber: 2,
		physicalAttack: 3,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 3,
		fame: 2,
		fortified: true,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Cursed Hags',
		tokenNumber: 3,
		physicalAttack: 3,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 5,
		fame: 3,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: true,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Cursed Hags',
		tokenNumber: 3,
		physicalAttack: 3,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 5,
		fame: 3,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: true,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Wolf Riders',
		tokenNumber: 4,
		physicalAttack: 3,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 4,
		fame: 3,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Wolf Riders',
		tokenNumber: 4,
		physicalAttack: 3,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 4,
		fame: 3,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Ironclads',
		tokenNumber: 5,
		physicalAttack: 4,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 3,
		fame: 4,
		fortified: false,
		physicalResist: true,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Ironclads',
		tokenNumber: 5,
		physicalAttack: 4,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 3,
		fame: 4,
		fortified: false,
		physicalResist: true,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Orc Summoners',
		tokenNumber: 6,
		physicalAttack: 0,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 4,
		fame: 4,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: true,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Orc Summoners',
		tokenNumber: 6,
		physicalAttack: 0,
		fireAttack: 0,
		iceAttack: 0,
		coldFireAttack: 0,
		defense: 4,
		fame: 4,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: true,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	
];