export default mauraudingOrcs = [
	{
		name: 'Prowlers',
		number: 1,
		attack: {
			normal: 4,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 3,
		fame: 2,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Prowlers',
		number: 1,
		attack: {
			normal: 4,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 3,
		fame: 2,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Diggers',
		number: 2,
		attack: {
			normal: 3,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 3,
		fame: 2,
		fortified: true,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Diggers',
		number: 2,
		attack: {
			normal: 3,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 3,
		fame: 2,
		fortified: true,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Cursed Hags',
		number: 3,
		attack: {
			normal: 3,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 5,
		fame: 3,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: true,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Cursed Hags',
		number: 3,
		attack: {
			normal: 3,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 5,
		fame: 3,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: false,
		poison: true,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Wolf Riders',
		number: 4,
		attack: {
			normal: 3,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 4,
		fame: 3,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Wolf Riders',
		number: 4,
		attack: {
			normal: 3,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 4,
		fame: 3,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: true,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Ironclads',
		number: 5,
		attack: {
			normal: 4,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 3,
		fame: 4,
		fortified: false,
		physicalResist: true,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Ironclads',
		number: 5,
		attack: {
			normal: 4,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 3,
		fame: 4,
		fortified: false,
		physicalResist: true,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: false,
		swift: false,
		brutal: true,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Orc Summoners',
		number: 6,
		attack: {
			normal: 0,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 4,
		fame: 4,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: true,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	{
		name: 'Orc Summoners',
		number: 6,
		attack: {
			normal: 0,
			fire: 0,
			ice: 0,
			coldFire: 0
		},
		defense: 4,
		fame: 4,
		fortified: false,
		physicalResist: false,
		fireResist: false,
		iceResist: false,
		comboResist: false,
		elusive: false,
		unfortified: false,
		arcaneImmunity: false,
		summonAttack: true,
		swift: false,
		brutal: false,
		poison: false,
		paralyze: false,
		assassination: false,
		cumbersome: false,
		vampiric: false
	},
	
];